
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
   oauth2:
     client:
       registration:
         google:
           client-id: 504998354063-rivs6ama7j4ojniccg4irbnrg51osbso.apps.googleusercontent.com
           client-secret: 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
           scope:
             - email
             - profile

         facebook:
           client-id: 769477157872068
           client-secret: e108b8266b8d875d9ba39ec0b39a6c55
           scope:
             - email
             - public_profile

         naver:
           client-id: SNNV60Zc_kD8lsjISHhM
           client-secret: 9Ulb_GLOvP
           scope:
             - name
             - email
           client-name: Naver
           authorization-grant-type: authorization_code
           redirect-uri: http://localhost:8080/login/oauth2/code/naver

       provider:
         naver:
           authorization-uri: https://nid.naver.com/oauth2.0/authorize
           token-uri: https://nid.naver.com/oauth2.0/token
           user-info-uri: https://openapi.naver.com/v1/nid/me
           user-name-attribute: response # 회원정보를 Json으로 받는데 response라는 키값으로 리턴받음

logging:
  level:
    org.hibernate.SQL: debug